---
- name: For build server
  hosts: all
  become: yes

  tasks:
  - name: Ensure packages installed
    apt:
      pkg:
      - git
      - default-jdk
      - maven
      - docker.io
      - python3-pip
      state: present
      update_cache: true

  - name: clone from github
    git:
      repo: https://github.com/miladhub/calculator-servlet-example
      dest: /tmp/calculator-servlet-example/
      clone: yes

  - name: build app
    command: mvn --batch-mode --quiet install
    args:
     chdir: /tmp/calculator-servlet-example/

  - name: install docker plugin
    pip:
      name: docker

  - name: Creating Dockerfile
    copy:
      dest: /tmp/calculator-servlet-example/target/Dockerfile
      content: |
        FROM: tomcat:9.0.72-jre11
        ADD mycalcwebapp.war /usr/local/tomcat/webapps/

  - name: Build an image and push it to a private repo
    community.docker.docker_image:
      build:
        path: /tmp/calculator-servlet-example/target
      push: true
      source: build
