---
- name: For build server
  hosts: all
  become: yes

  tasks:
  - name: Ensure packages installed
    apt:
      pkg:
      - git
      - default-jdk
      - maven
      - docker.io
      state: present
      update_cache: true

  - name: clone from github
    git:
      repo: https://github.com/miladhub/calculator-servlet-example
      dest: /tmp/calculator-servlet-example/
      clone: yes

  - name: build app
    command: mvn --batch-mode --quiet install
    args:
     chdir: /tmp/calculator-servlet-example/

  - name: Pull an image
    community.docker.docker_image:
      name: tomcat:9.0.72-jre11
      source: pull
      pull:

  - name: Tag and push to docker hub
    community.docker.docker_image:
      name: tomcat:9.0.72-jre11
      push: true
      source: local