---
    - name: Provision for prod server
      hosts: all
      become: yes
    
      tasks:
      - name: Ensure that packages installed
        apt:
          pkg:
          - docker.io
          - python3-pip
          state: present
          update_cache: true

      - name: Install docker pip plugin
        pip:
          name: docker

      - name: Pull app image from Docker Hub
        community.docker.docker_image:
          build:
            path: /tmp/calculator-servlet-example/target/
          name: nikolaidav/certify
          tag: latest
          source: pull
    
      - name: Run app
        community.docker.docker_container:
          name: mycalc
          image: httpd
          state: started
          detach: true
          exposed_ports:
            - 80
          ports:
            - 8080:80