---
    - name: Provision for prod server
      hosts: all
      become: yes
    
      tasks:
      - name: Ensure that packages installed
        apt:
          pkg:
          - docker.io
          - python3-pip
          state: present
          update_cache: true

      - name: Install docker pip plugin
        pip:
          name: docker

      - name: Pull app image from Docker Hub
        community.docker.docker_image:
          name: nikolaidav/certify
          tag: v1
          source: pull
    
      - name: Run app
        community.docker.docker_container:
          name: mycalcwebapp
          image: nikolaidav/certify
          state: started
          detach: true
          ports:
            - 8080:8080
